spring:
  application:
    name:
      fisher

  profiles:
    active: prod

apify:
  actor-id:
    instagram-comment:
      SbK00X0JYCPblD2wp
    instagram-profile:
      dSCLg0C3YEZ83HzYX
    instagram-post:
      nH2AHrwxeTRJoN5hX
    facebook-comment:
      us5srxAYnsrkgUv2v
    facebook-post:
      KoJrdxJCTtpon81KY
    facebook-profile:
      8BRR4FaIO1IrCi7KM
    tiktok-comment:
      BDec00yAmCm1QbMEI

server:
  port: 8080
